function xd = fg_chua(u,x1,x2,x3)
%FG_CHUA
%    XD = FG_CHUA(U,X1,X2,X3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    06-Apr-2020 18:40:05

xd = [x1.*(2.08e+2./1.25e+2)+x2.*(5.2e+1./5.0)-x1.^3.*4.264e-1;u+x1-x2+x3;x2.*(-3.3e+1./2.0)-x3./1.0e+1];
