function u = u_chua(in1)
%U_CHUA
%    U = U_CHUA(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    16-Apr-2020 16:25:56

v = in1(1,:);
x1 = in1(2,:);
x2 = in1(3,:);
x3 = in1(4,:);
u = v.*(5.0./5.2e+1)-x1+x2-x3+(x1.^2.*1.31664-2.0176).*(x1.*2.0176+x2.*(5.2e+1./5.0)-x1.^3.*4.3888e-1).*(5.0./5.2e+1);
